# Generated by Django 3.1.7 on 2021-07-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=70)),
                ('password', models.CharField(max_length=70)),
                ('confirm_password', models.CharField(max_length=70)),
                ('Address', models.CharField(max_length=70)),
            ],
        ),
        migrations.AddField(
            model_name='login',
            name='password',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
